### ISSUE TITLE
Here's your coding interview problem - HacktoberFest2020 [Medium]

### ISSUE THREAD

**Issue by LifeofAGeek** [LifeofAGeek/Interview-Problem-Statements#5]
This problem was asked by Airbnb.

Given an array of integers, return the largest range, inclusive, of integers that are all included in the array.

For example, given the array [9, 6, 1, 3, 8, 10, 12, 11], return (8, 12) since 8, 9, 10, 11, and 12 are all in the array.

**Comment by hmnt007** [comment]
I'm working on this issue..

**Comment by Tripathi-Alok** [comment]
Can i work on this problem

**Comment by LifeofAGeek** [comment]
> Can i work on this problem

Yes please
